version: "3.9"

networks:
  backend-net:

services:
  # Category Service + DB
  category-db:
    image: postgres:15
    container_name: category-db
    environment:
      POSTGRES_USER: category
      POSTGRES_PASSWORD: category123
      POSTGRES_DB: category
    ports:
      - "5433:5432"
    networks:
      - backend-net

  # Event Service + DB
  event-db:
    image: postgres:15
    container_name: event-db
    environment:
      POSTGRES_USER: event
      POSTGRES_PASSWORD: event123
      POSTGRES_DB: event
    ports:
      - "5434:5432"
    networks:
      - backend-net

  # User Service + DB
  user-db:
    image: postgres:15
    container_name: user-db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: user123
      POSTGRES_DB: user
    ports:
      - "5435:5432"
    networks:
      - backend-net
      -
  # Request Service + DB
  request-db:
    image: postgres:15
    container_name: request-db
    environment:
      POSTGRES_USER: request
      POSTGRES_PASSWORD: request123
      POSTGRES_DB: request
    ports:
      - "5436:5432"
    networks:
      - backend-net

  # Compilation Service + DB
  compilation-db:
    image: postgres:15
    container_name: compilation-db
    environment:
      POSTGRES_USER: compilation
      POSTGRES_PASSWORD: compilation123
      POSTGRES_DB: compilation
    ports:
      - "5437:5432"
    networks:
      - backend-net

  # Comment Service + DB
  comment-db:
    image: postgres:15
    container_name: comment-db
    environment:
      POSTGRES_USER: comment
      POSTGRES_PASSWORD: comment123
      POSTGRES_DB: comment
    ports:
      - "5438:5432"
    networks:
      - backend-net

  # Stats Server + DB
  stats-db:
    image: postgres:15
    container_name: stats-db
    environment:
      POSTGRES_USER: stats
      POSTGRES_PASSWORD: stats123
      POSTGRES_DB: stats
    ports:
      - "5439:5432"
    networks:
      - backend-net

